services:
  mariadb:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    healthcheck:
      test: [ 'CMD', 'mariadb', '-u', 'root', '-p$MARIADB_ROOT_PASSWORD', '-e', 'SHOW DATABASES' ]
      interval: 5s
      timeout: 5s
      retries: 3
  landing-renderer:
    image: php:8-apache
    volumes:
      - ./landings:/var/www/html/landings
  backend:
    build:
      context: .
      dockerfile: infra/core.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_HOST: mariadb
    ports:
      - '8000:5000'
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./landings:/app/landings
    links:
      - mariadb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:5000/api/v2/health" ]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 120s
