services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test1234
      MARIADB_DATABASE: bangi_local_dev
    ports:
      - '3306:3306'
    healthcheck:
      test: [ 'CMD', 'mariadb', '-u', 'root', '-p$MARIADB_ROOT_PASSWORD', '-e', 'SHOW DATABASES' ]
      interval: 5s
      timeout: 5s
      retries: 3
  backend:
    build:
      context: .
      dockerfile: infra/core.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '8000:5000'
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
